### ISSUE TITLE
如何使用docker-compose创建数据库

### ISSUE THREAD

**Issue by katherine0325** [katherine0325/katherine0325.github.io#29]
## 前言
在开发过程中，我们常常需要在本地创建数据库并初始化一些数据方便开发。

而当我们遇到一些新项目的时候，这些数据库或数据表是原本我们没有的，我就就需要为这些数据库环境作出一些努力，如果有一个命令，可以一键将所需数据库通过docker启动起来就好了。

就是有这么方便的东西

## 一、创建文件
在根目录创建docker-compose文件 docker-compose.yml

![图片](https://uploader.shimo.im/f/z5l64RGs3Cc2bvRm.png!thumbnail)

## 二、代码
```
version: "3"
services:
    mssql:
        image: microsoft/mssql-server-linux:2017-latest
        ports:
            - "1433:1433"
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Reg@)!&!!!!"
    mongo:
        image: mongo:3.6-jessie
        ports:
            - "27017:27017"
    pg:
        image: postgres:9.6.6
        ports:
            - "5421:5432"
        environment:
            POSTGRES_PASSWORD: "Reg@)!&!!!!"
            POSTGRES_USER: "registry"
```
以上代码，我启动了3个数据库，分别是 sqlserver，mongo，postgrep
自定义名字根据案例为：mssql/mongo/pg

image：表示所需要的数据库镜像

ports：将数据库接口映射到本地（其中写在前面的是本地的port，后面的是原有的port）

其中，sqlserver数据库在初始化的时候通过环境变量指定密码（环境变量key name如上所示），到时候登陆的时候用户名是默认用户名：sa，密码是指定密码，数据库是master

同样，postgrep数据库也需要通过环境变量指定一些创建数据库的值

## 三、启动
```
docker-compose up
```
通过命令即可将以上数据库启动起来，可以继续开发了
通过这个方式启动起来的：

docker container 名字为项目名 + 数据库自定义名（所以不用担心container重名问题）

数据库在命令执行窗口维持运行，当退出命令时docker container stop

数据库在二次启动（即下一次的 docker-compose up）会维持上一次创建好的数据库以及数据
