### ISSUE TITLE
如何创建一个React前端项目

### ISSUE THREAD

**Issue by katherine0325** [katherine0325/katherine0325.github.io#34]
### 前言

这是一个简单的react项目，从零开始创建一个博客，帮助学习react到完成一个完整的项目。

案例项目代码地址：[https://github.com/katherine0325/react-ui-article](https://github.com/katherine0325/react-ui-article)

### 

### 一、创建项目

安装create-react-app包

```shell
npm i create-react-app -g
```
创建项目
```shell
create-react-app ui-article
```
>这个过程可能需要耗费一些时间，请耐心等待

### 二、创建页面

在src中创建pages文件夹，并在其下创建页面

src/pages/home/index.js

```javascript
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import ArticleLine from '../../components/article-line';
import { getArticleList } from './service';
import { message } from 'antd';
import './index.css';
export default function Home() {
  const [list, setList] = useState([]);
  useEffect(() => {
    init();
  }, [])
  async function init() {
    const loading = message.loading('加载中...');
    const result = await getArticleList();
    setList(result);
    setTimeout(loading, 0);
  }
  function handleBtnClick() {
    document.location.hash = '#detail';
  }
  return (
    <div className='home'>
      {list.map((item, index) => 
        <Link to={'/article?article_number=' + item.number} key={item.id}>
          <ArticleLine number={index + 1} title={item.title} date={item.created_at.slice(0, 10)}></ArticleLine>
        </Link>
      )}
    </div>
  )
}
```
src/pages/home/index.css

```css
.home a {
  text-decoration: none;
  color: #444;
}
```
http请求均在本文件中完成，使用axios进行http请求

src/pages/home/service.js

```javascript
import Axios from 'axios'
export const getArticleList = async () => {
  const result = await Axios.get('https://api.github.com/repos/katherine0325/katherine0325.github.io/issues')
  return result.data
}
```
>除了本项目除了home页面还有article页面，请直接查看案例项目代码补充

### 三、连接路由

home页面创建之后，需要在App.js中添加路由

src/App.js

```javascript
import React, { lazy, Suspense } from "react";
import { BrowserRouter as Router, Route } from "react-router-dom";
import 'antd/dist/antd.css';
import DefaultLayout from './layout/default';
const Home = lazy(() => import('./pages/home'));
const Article = lazy(() => import('./pages/article'));
const AppRouter = () => (
  <Router>
    <Suspense fallback={<div>加载中...</div>}>
      <DefaultLayout path="/" exact component={Home} />
      <DefaultLayout path="/article" component={Article} />
    </Suspense>
  </Router>
);
export default AppRouter;
```
这里涉及到三个知识点：

* 使用react-router-dom添加路由
* 使用按需加载提高react应用的性能
* 为页面添加默认layout
1. 使用react-router-dom添加路由

我们可以用以下方式添加路由：

```javascript
import React from 'react';
import { BrowserRouter as Router, Route } from 'react-router-dom';
import Home from './pages/home';
import Article from './pages/article';
export default AppRouter = () => (
  <Router>
    <div>
      <!-- exact 表示默认页面 -->
      <Route path="/" exact component={Home} />
      <Route path="/article" exact component={Article} />
    </div>
  </Router>
)
```
2. 使用按需加载提高react应用的性能

按需加载在React应用中提高性能是非常有意义的事情，(这里查找一下按需加载的定义和意义）

按需加载需要把`import Home from './pages/home'`使用import方法引入，并且使用React的lazy将其进行加载，React.lazy方法可以异步加载组件文件。React.lazy不能单独使用，需要配合React.suspense，suspence是用来包裹异步组件，添加loading效果等。

```javascript
import React from 'react';
import { BrowserRouter as Router, Route } from 'react-router-dom';
const Home = lazy(() => import('./pages/home'));
const Article = lazy(() => import('./pages/article')
export default AppRouter = () => (
  <Router>
    <Suspense fallback={<div>加载中...</div>}>
      <Route path="/" exact component={Home} />
      <Route path="/article" exact component={Article} />
    </Suspense>
  </Router>
)
```
3. 为页面添加默认layout

通常我们的网页中，顶部的菜单栏都是统一的，我们没有必要为每一个页面添加一遍菜单栏组件，只需要整体使用一个layout，然后在其内部添加路由页面即可。

本次项目中，我们引入import DefaultLayout from './layout/default';，然后将Route组件替换为DefaultLayout。

我们看一下default layout的代码

src/layout/default.js

```javascript
import React, { Component } from "react";
import generateLayout from '../lib/generate-layout';
import './default.css';
class Default extends Component {
    render() {
        return (
            <div className='layout-default'>
              <div className="header">
                <div className="dark">
                  <h1>Katherine的技术博客</h1>
                </div>
              </div>
              <div className="section">
                <div className="main">
                  {this.props.children}
                </div>
                {/* <p className="github-site">本项目为React前端项目，代码地址：<a href="https://github.com/katherine0325/react-ui-article" target="_blank">https://github.com/katherine0325/react-ui-article</a></p> */}
              </div>
            </div>
        )
    }
}
export default generateLayout(Default);
```
src/layout/default.css

```css
/* * {
  margin: 0;
  padding: 0;
} */
.layout-default .header {
  height: 300px;
  background-image: linear-gradient(135deg,#79f1a4,#0e5cad);
  text-align: center;
  display: flex;
  align-items: flex-end;
}
.layout-default .header .dark {
  margin: 0 auto;
  width: 800px;
  height: 150px;
  background-color: rgba(8,105,132,.52);
  border-top-left-radius: 4px;
  border-top-right-radius: 4px;
}
.layout-default .header .dark h1 {
  line-height: 120px;
  display: block;
  font-size: 2.4em;
  -webkit-margin-before: 0.67em;
  -webkit-margin-after: 0.67em;
  -webkit-margin-start: 0px;
  -webkit-margin-end: 0px;
  font-weight: bold;
  color: #a9e4f5;
}
.layout-default .section {
  background-color: #f7f8fa;
  padding-bottom: 60px;
}
.layout-default .section .main {
  margin: 0 auto;
  width: 800px;
  background: #fff;
  box-shadow: 0 1px 2px 0 rgba(0,0,0,.05);
  border-bottom-left-radius: 4px;
  border-bottom-right-radius: 4px;
}
.layout-default .section .github-site {
  padding: 35px 0;
  text-align: center;
}
```
再通过放在lib中的一个generate-layout文件将default layout组件之后的页面路由组件结合起来

src/lib/generate-layout.js

```javascript
import React from "react";
import { Route } from "react-router-dom";
export default Layout => {
    return ({component: Component, ...rest}) => {
        return (
            <Route {...rest} render={matchProps => (
                <Layout children={<Component {...matchProps} />}></Layout>
            )} />
        )
    };
}
```

### 四、创建组件

从上面的页面可以看出，home页面使用了一个叫做ArticleLine的组件，使得主页中列出的文章标题都可以复用这个组件，那么我们可以：

src/components/article-line/index.js

```javascript
import React from 'react';
import './index.css';
export default function ArticleLine({number, title, date}) {
  return (
    <div class="article-line">
      <div class="number">{number}</div>
      <div class="title">{title}</div>
      <div class="date">{date}</div>
    </div>
  )
}
```
src/components/article-line/index.css

```css
.article-line {
  padding: 30px 15px;
  border-bottom: 1px solid #f5f5f5;
  display: grid;
  grid-template-columns: 50px auto 100px;
  align-items: center;
}
.number {
  flex-basis: 80px;
  text-align: center;
  -ms-flex-negative: 0;
  flex-shrink: 0;
  font-weight: 700;
  color: rgba(11, 96, 119, 0.52);
  font-size: 17px;
}
.title {
  font-family: inherit;
  font-weight: 500;
  line-height: 1.2;
  color: #444;
  font-size: 16px;
}
.date {
  font-size: 13px;
  font-weight: 500;
  color: #87878a;
  line-height: 1.2;
}
```

### 五、引用antd框架

antd框架的组件库文档：[https://3x.ant.design/docs/react/introduce-cn](https://3x.ant.design/docs/react/introduce-cn)

在App.js中引入antd的css文件，那么后面当我们引用antd的组件时，便会有antd的样式了

App.js

```javascript
import 'antd/dist/antd.css';
```
之后在项目中各个需要组件的地方直接引用antd的组件，举例如下：

```plain
import { Button } from 'antd';
...
<Button>Submit</Button>
...
```

### END

这样一个简单的react项目就创建完了
